[package]
name = "waitfor"
version = "0.2.1"
authors = ["Adam Shirey <adam@shirey.ch>"]
edition = "2021"


[profile.release]
lto = true
codegen-units = 1
panic = "abort"


[dependencies]
clap = "2.33.3"
url = "2.2.0"
waitforit = "0.1"
